sudo:
  - false
language: node_js
node_js:
  - 'node'
services:
  - mysql
env:
  - secrets.dbpassword = abcd1234 secrets.host = rds-mysql-discollectdb.c0eor5cjwn0u.us-west-1.rds.amazonaws.com secrets.port 3306
install:
  - npm install
  - npm start
script: 
  - npm test

# after_script:
# - echo "Build Finished!"
