# sudo:
#   - false
# language: node_js
# node_js:
#   - '5.8'
# services:
#   - mysql
# env:
#   - USERNAME = travis PASSWORD = '' DATABASE = moodb
# before_install:
#   - mysql -e "CREATE DATABASE IF NOT EXISTS moodb;" -u root #install database for user 'travis'
# before_script:
#   - npm install -g webpack
#   - npm install -g mocha
#   - npm install -g chai
#   - babel-node server/index.js
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - sleep 3 #delay start of xvfb
# after_script:
# - echo "Build Finished!"